### ISSUE TITLE
Todos

### ISSUE THREAD

**Issue by suppHorter** [suppHorter/bayreuthescape#1]
## Todos:
- [ ] set correct countdown after reload
  - [ ] create php database endpoint
  - [ ] investigate why "currenttime" is always 00:00
  - [ ] fetch endpoint to frontend
- [ ] admin page
  - [ ] fix dropdown song
  - [ ] fix UI for file upload

##  Todos in Planung:
 - [ ] setup script mit automatischem update (von dediziertem USB)
   - [ ] aufräumen von Apache cache (op-cache)
   - [ ] Dateien updaten (webserver, datenbank, python)
   - [ ] auto-restart python scripts
- [ ] upgrade auf neue Hardware [raspberry 4](https://www.berrybase.de/raspberry-pi-4-computer-modell-b-4gb-ram)
  - [ ] aktuelles setup ist nachvollziehbar dokumentiert
  - [ ] SD Karten vorbereiten (per script?)

## Fehlende Grundlagen:
- [ ] Datenbank Backup
  - [ ] Speicherort / medium (NAS / Windows-PC's / ...)
- [ ] (Logging für spätere Fehlersuche)
 - [ ] health cronjob
